version: '2'
services:
  database:
    image: postgres:12-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=license
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - /home/gledisgjinaj/postgres-data:/var/lib/postgresql/data

  eureka-server:
    image: ggjinaj/eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8761"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"

  config-server:
    image: ggjinaj/config-server:0.0.1-SNAPSHOT
    container_name: config-server
    mem_limit: 1000000000
    environment:
      PROFILE: "dev"
      EUREKA_SERVER_PORT: "8761"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"

  gateway-server:
    image: ggjinaj/gateway-server:0.0.1-SNAPSHOT
    container_name: gateway-server
    mem_limit: 1073741824
    ports:
      - "8072:8072"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8072"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"

  authentication-service:
    image: ggjinaj/authentication-service:0.0.1-SNAPSHOT
    container_name: authentication-service
    mem_limit: 1073741824
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8083"
      GATEWAY_SERVER_PORT: "8072"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"

  organization-service:
    image: ggjinaj/organization-service:0.0.1-SNAPSHOT
    container_name: organization-service
    mem_limit: 1073741824
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8081"
      GATEWAY_SERVER_PORT: "8072"
      AUTHENTICATION_SERVICE_PORT: "8083"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"

  licensing-service:
    image: ggjinaj/licensing-service:0.0.1-SNAPSHOT
    container_name: licensing-service
    mem_limit: 1073741824
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8082"
      GATEWAY_SERVER_PORT: "8072"
      AUTHENTICATION_SERVICE_PORT: "8083"
      CONFIG_SERVER_URI: "http://config-server:8888"
      CONFIG_SERVER_PORT: "8888"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"