apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: authentication-service
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: authentication-service
  strategy: {}
  template:
    metadata:
      labels:
        service: authentication-service
    spec:
      containers:
        - env:
            - name: CONFIG_SERVER_PORT
              value: "8888"
            - name: CONFIG_SERVER_URI
              value: http://config-server:8888
            - name: EUREKA_SERVER_PORT
              value: "8761"
            - name: EUREKA_SERVER_URI
              value: http://eureka-server:8761/eureka/
            - name: GATEWAY_SERVER_PORT
              value: "8072"
            - name: PROFILE
              value: aws
            - name: SERVER_PORT
              value: "8083"
          image: ggjinaj/authentication-service:latest
          name: authentication-service
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "1073741824"
      restartPolicy: Always
status: {}
