apiVersion: v1
kind: Service
metadata:
  labels:
    service: authentication-service
  name: authentication-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    service: authentication-service
status:
  loadBalancer: {}
