apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: config-server
  strategy: {}
  template:
    metadata:
      labels:
        service: config-server
    spec:
      containers:
        - env:
            - name: EUREKA_SERVER_PORT
              value: "8761"
            - name: EUREKA_SERVER_URI
              value: http://eureka-server:8761/eureka/
            - name: PROFILE
              value: aws
          image: ggjinaj/config-server:latest
          name: config-server
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: "1e9"
      restartPolicy: Always
status: {}
