apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: eureka-server
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eureka-server
  strategy: {}
  template:
    metadata:
      labels:
        service: eureka-server
    spec:
      containers:
        - env:
            - name: EUREKA_SERVER_URI
              value: http://eureka-server:8761/eureka/
            - name: PROFILE
              value: aws
            - name: SERVER_PORT
              value: "8761"
          image: ggjinaj/eureka-server:latest
          name: eureka-server
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
status: {}
