apiVersion: v1
kind: Service
metadata:
  labels:
    service: eureka-server
  name: eureka-server
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    service: eureka-server
status:
  loadBalancer: {}
