apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: gateway-server
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gateway-server
  strategy: {}
  template:
    metadata:
      labels:
        service: gateway-server
    spec:
      containers:
        - env:
            - name: CONFIG_SERVER_PORT
              value: "8888"
            - name: CONFIG_SERVER_URI
              value: http://config-server:8888
            - name: EUREKA_SERVER_PORT
              value: "8761"
            - name: EUREKA_SERVER_URI
              value: http://eureka-server:8761/eureka/
            - name: PROFILE
              value: aws
            - name: SERVER_PORT
              value: "8072"
          image: ggjinaj/gateway-server:latest
          name: gateway-server
          ports:
            - containerPort: 8072
          resources:
            limits:
              memory: "1073741824"
      restartPolicy: Always
status: {}
