apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway-server
  name: gateway-server
spec:
  type: NodePort
  ports:
    - name: "8072"
      protocol: TCP
      port: 8072
      targetPort: 8072
      nodePort: 31000
  selector:
    service: gateway-server
status:
  loadBalancer: {}
