apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: organization-service
  name: organization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: organization-service
  strategy: {}
  template:
    metadata:
      labels:
        service: organization-service
    spec:
      containers:
        - env:
            - name: AUTHENTICATION_SERVICE_PORT
              value: "8083"
            - name: CONFIG_SERVER_PORT
              value: "8888"
            - name: CONFIG_SERVER_URI
              value: http://config-server:8888
            - name: EUREKA_SERVER_PORT
              value: "8761"
            - name: EUREKA_SERVER_URI
              value: http://eureka-server:8761/eureka/
            - name: GATEWAY_SERVER_PORT
              value: "8072"
            - name: PROFILE
              value: aws
            - name: SERVER_PORT
              value: "8081"
          image: ggjinaj/organization-service:latest
          name: organization-service
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
      restartPolicy: Always
status: {}
