apiVersion: v1
kind: Service
metadata:
  labels:
    service: organization-service
  name: organization-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    service: organization-service
status:
  loadBalancer: {}
