server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/gledisi/config-repo.git
          searchPaths: licensing-service,organization-service,gateway-server,authentication-service
          username: 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
          password:
encrypt:
     key: IMSYMMETRIC
##Setting logging levels
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    city.ac: DEBUG
